Vagrant.configure("2") do |config|
  config.vm.box = "mvi-builder-0m18"

  config.ssh.username = 'root'
  config.ssh.password = 'tribblix'
  config.ssh.insert_key = true

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision :shell do |s|
    s.privileged = false
    s.env = {
      :all_proxy => ENV["all_proxy"],
      :http_proxy => ENV["http_proxy"],
      :https_proxy => ENV["https_proxy"],
      :no_proxy => "16.0.96.20"
    }
    s.inline = <<-SHELL
      mkdir -p /packages/localsrc/Tribblix/mvi
      wget "https://github.com/ptribble/mvi/archive/master.tar.gz" -O- | tar xvz -C /packages/localsrc/Tribblix/mvi --strip 1
      wget "https://github.com/juaningan/parsec-mvi/archive/master.tar.gz" -O- | tar xvz -C /packages/localsrc/Tribblix/mvi --strip 1
      sed -i 's/DISTVER=17/DISTVER=18/g' /packages/localsrc/Tribblix/mvi/mvi.sh
    SHELL
  end
end
