@startuml
start
if (detect_hostname) then (0)
else (1)
  stop
endif
if (detect_network) then (0)
else (1)
  stop
endif
if (detect_ipaddress) then (static)
else (dhcp)
endif
:config_network;
:create_dir;
if (detect_disk) then (0)
  while (check_disk) is (1)
    :prepare_disk;
  endwhile (ok)
    :mount_disk;
else (1)
  :mount_diskless;
endif

if (check_online) then (0)
  :update_app;
else (1)
endif

if (check_app) then (0)
  :deploy_app;
else (1)
  stop
endif

stop
@enduml
