@startuml
title TCE\n Components Diagram
skinparam componentStyle uml2

actor Operador
actor Desarrollador

cloud "Efficient" {
  [DHCP]
  [ipam\nTCP:80] as IPAM80
}

node "repomirror" {
  [tce2git]
  [webserver\nHTTP:80] as WEB80
  [webserver\nSSH:22] as WEB22
  [gitea\nHTTP:3000] as GITEA3000
  [gitea\nGIT:22] as GITEA22
  [ipxe-ipam\nHTTP:4777] as IPXE4777
}

node "consul" {
  [consul\nHTTP:8500] as CONSUL8500
}

cloud "fronts" {
  [fronts\nSSH:22] as FRONTS22
}

cloud "TCEs" {
  [tce]
}

cloud "webmin" {
  [webmin\nHTTP:80] as WEBMIN80
}

node "parsec" {
  [tftp\nUDP:69] as TFTP69
}

cloud "internet" {
  [github.com]
  [tribblix.org]
}

node "CI" {
  [concourse.ci]
  [packer]
}

Operador -> IPAM80
Operador -> WEBMIN80
Desarrollador -> github.com : cambios
[tce] -> DHCP
[tce] -> TFTP69
[tce] -> WEB80
[tce] -> IPXE4777
[tce] -> GITEA3000
IPXE4777 -> IPAM80
IPXE4777 -> CONSUL8500
WEBMIN80 -> CONSUL8500
[tce2git] -> FRONTS22
[tce2git] -> GITEA22
[packer] -> WEB22
[concourse.ci] -> [github.com] : observa
[concourse.ci] -> [packer] : ejecuta
[packer] -> [tribblix.org]
@enduml
