@startuml
title TCE\n Components Diagram
skinparam componentStyle uml2

actor Operador
actor Desarrollador
actor tce2git

cloud "Efficient" {
  [DHCP]
  [ipam\nTCP:80] as IPAM80
}

node "repomirror" {
  [webserver\nHTTP:80\nSCP:22] as WEB80
  [gitea\nHTTP:3000\nGIT:22] as GITEA
  [ipxe-ipam\nHTTP:4777] as IPXE4777
}

node "consul" {
  [consul\nHTTP:8500] as CONSUL8500
}

cloud "fronts" {
  [fronts\nSCP:22] as FRONTS22
}

cloud "TCEs" {
  [tce]
}

cloud "webmin" {
  [webmin\nHTTP:80] as WEBMIN80
}

node "parsec" {
  [tftp\nUDP:69] as TFTP69
}

cloud "internet" {
  [tribblix.org]
}

cloud "LDAP" {
  [LDAP\nTCP:389] as LDAP389
}

node "CI" {
  [concourse.ci]
  [packer]
}

Operador -> IPAM80
Operador -> WEBMIN80
Desarrollador -> GITEA : cambios
[tce] -> DHCP
[tce] -> TFTP69
[tce] -> WEB80
[tce] -> IPXE4777
IPXE4777 -> IPAM80
IPXE4777 -> CONSUL8500
WEBMIN80 -> CONSUL8500
tce2git -> FRONTS22
tce2git -> GITEA
GITEA -> LDAP389
[packer] -> WEB80
[concourse.ci] -> GITEA : observa
[concourse.ci] -> [packer] : ejecuta
[packer] -u-> [tribblix.org]
@enduml
