#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2012, Joyent, Inc. All rights reserved.
#
. /lib/svc/share/smf_include.sh

source /home/metro/environment

DRIVER_NAME="digi_realport"
RPDAEMON="/usr/bin/ncxd"
RPMKNODS="/usr/bin/ncx_mknod"
RPMKLINKS="/usr/bin/ncx_make_links"

DFT_IP_PORT=771

tty_dir_name="dty"
txprint_dir_name="dpr"
cua_dir_name="cua"
term_dir_name="term"

get_major() {
 major_number=0
 while read name major; do
   if [[ ${name} = ${DRIVER_NAME} ]]; then
     major_number=$major
     break
   fi
 done < /etc/name_to_major
}

get_major

uis_ip=${UIS_IP}
psn=0
devid="EL"
ndev=16
secureopt="never"

$RPMKNODS ${major_number} ${psn} ${devid} ${ndev} ${tty_dir_name} ${txprint_dir_name}
$RPMKLINKS "/dev/${tty_dir_name}" ${devid} "s" ${ndev} "/dev/${cua_dir_name}"
$RPMKLINKS "/dev/${tty_dir_name}" ${devid} "m" ${ndev} "/dev/${term_dir_name}"

ln -sf /dev/dty/${devid}001s /dev/ttys01
ln -sf /dev/dty/${devid}002s /dev/ttys02
ln -sf /dev/dty/${devid}003s /dev/ttys03
ln -sf /dev/dty/${devid}004s /dev/ttys04
ln -sf /dev/dty/${devid}005s /dev/ttys05
ln -sf /dev/dty/${devid}006s /dev/ttys06
ln -sf /dev/dty/${devid}007s /dev/ttys07
ln -sf /dev/dty/${devid}008s /dev/ttys08
ln -sf /dev/dty/${devid}009s /dev/ttys09
ln -sf /dev/dty/${devid}010s /dev/ttys10
ln -sf /dev/dty/${devid}011s /dev/ttys11
ln -sf /dev/dty/${devid}012s /dev/ttys12
ln -sf /dev/dty/${devid}013s /dev/ttys13
ln -sf /dev/dty/${devid}014s /dev/ttys14
ln -sf /dev/dty/${devid}015s /dev/ttys15
ln -sf /dev/dty/${devid}016s /dev/ttys16

$RPDAEMON -d /dev/${DRIVER_NAME}${psn} -i ${uis_ip} -p $DFT_IP_PORT -e $secureopt

exit $SMF_EXIT_OK
