Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "op30"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vbguest.auto_update = false
  config.vm.provision :file do |f|
    f.source = "files"
    f.destination = "/tmp/"
  end
  config.vm.provision :shell do |s|
    s.path = "scripts/runtime/poi.sh"
    s.env = {
      :all_proxy => ENV["all_proxy"],
      :http_proxy => ENV["http_proxy"],
      :https_proxy => ENV["https_proxy"],
      :no_proxy => "16.0.96.20"
    }
  end
  config.vm.provision "shell", path: "scripts/app/tce.sh"
  config.vm.provision "shell", path: "scripts/root/poi10.sh"
end
