resources:
- name: resource-mkosi-wrapper
  type: git
  source:
    uri: https://github.com/juaningan/metro-parsec
    paths: [ packer/mkosi-wrapper ]

- name: resource-mkosi-guacamole
  type: git
  source:
    uri: https://github.com/juaningan/metro-parsec
    paths: [ mkosi/guacamole ]

- name: resource-guacamole-server
  type: git
  source:
    uri: https://github.com/apache/guacamole-server

- name: resource-guacamole-client
  type: git
  source:
    uri: https://github.com/apache/guacamole-client

jobs:
- name: job-mkosi-guacamole
  plan:
  - aggregate:
    - get: resource-mkosi-wrapper
    - get: resource-mkosi-guacamole
    - get: resource-guacamole-server
    - get: resource-guacamole-client
  - task: task-mkosi-guacamole
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: juaningan/metro-ci}
      params:
        PACKER_LOG: 0
        WORKDIR: resource-mkosi-guacamole/mkosi/guacamole
      inputs:
        - name: resource-mkosi-guacamole
      run:
        path: packer
        dir: resource-mkosi-guacamole/packer/mkosi-wrapper
        args: [ "build", "mkosi-wrapper.json" ]
