#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2012, Joyent, Inc. All rights reserved.
#
. /lib/svc/share/smf_include.sh

diskdir=/.disk
hostname=$(uname -n)

check_online () {
  echo "INFO: Comprobando conectividad (10s)" > /dev/msglog
  ping 16.0.96.20 10
}

update_app () {
  if ! diff /metadata.json ${diskdir}/metadata.json >/dev/null ; then
    echo "INFO: Actualizando version de boot_archive" > /dev/msglog
    /usr/bin/wget -q "http://16.0.96.20/repo/pctce/boot_archive" -O ${diskdir}/platform/i86pc/boot_archive
    cp /metadata.json ${diskdir}/metadata.json
  fi
  echo "INFO: Descargando aplicacion" > /dev/msglog
  /usr/bin/wget -q "http://16.0.96.20/repo/pctce/pctce-app.tar.gz" -O ${diskdir}/pctce-app.tar.gz
  echo "INFO: Descargando configuracion" > /dev/msglog
  /usr/bin/wget -q "http://16.0.96.20/repo/tce-estacion/${hostname}/${hostname}.tar.gz" -O ${diskdir}/pctce-config.tar.gz
}

check_app () {
  echo "INFO: Comprobando ficheros aplicacion" > /dev/msglog
  if [[ ! -f ${diskdir}/pctce-config.tar.gz ]]; then
    echo "ERROR: No hay configuracion en el disco y tampoco se puede obtener por red" > /dev/msglog
    exit $SMF_EXIT_ERR_FATAL
  fi
}

deploy_app () {
  echo "INFO: Extrayendo aplicacion" > /dev/msglog
  /usr/gnu/bin/tar -C / -xzf ${diskdir}/pctce-app.tar.gz
  echo "INFO: Extrayendo configuracion" > /dev/msglog
  /usr/gnu/bin/tar -C / -xzf ${diskdir}/pctce-config.tar.gz
}

detect_uis () {
  uis_count=$(/usr/bin/awk '/UIS/ {print $1}' /etc/hosts | wc -l)
  if [[ $uis_count -ne '1' ]]; then
    echo "ERROR: No se puede determinar IP de la UIS por haber ${uis_count} coincidencias en /etc/hosts" > /dev/msglog
    exit $SMF_EXIT_ERR_FATAL
  else
    uis_ip=$(/usr/bin/awk '/UIS/ {print $1}' /etc/hosts)
    echo "INFO: IP de la UIS: ${uis_ip}" > /dev/msglog
  fi
}

detect_cancela () {
  cancela_port=$(/usr/bin/awk '/CANCELA/ {print $3}' /home/metro/sistema/V/CfgEquipo.CFG | /usr/bin/sed 's/^0*//')
  if [[ ! $cancela_port ]]; then
    echo "WARN: Sin cancela definida en CfgEquipo.CFG" > /dev/msglog
    cancela="false"
    rm -f /home/metro/sun/cancela_schneider
    rm -f /home/metro/sun/cancela_mayser
    return
  elif [[ $cancela_port -le 16 ]]; then
    echo "INFO: Cancela por UIS (binario: cancela_mayser)" > /dev/msglog
    cancela="uis"
    ln -sf cancela_mayser /home/metro/sun/cancela
    rm -f /home/metro/sun/cancela_schneider
  else
    echo "INFO: Cancela por Maestra (binario: cancela_schneider)" > /dev/msglog
    cancela="maestra"
    ln -sf cancela_schneider /home/metro/sun/cancela
    rm -f /home/metro/sun/cancela_mayser
  fi
}

detect_mbt () {
  concen_mbt_ip=$(/usr/bin/awk '/concen-mbt-ppp$/ {print $1}' /etc/hosts)
  mbt_ip=$(/usr/bin/awk '/mbt$/ {print $1}' /etc/hosts)
  if [[ -z $mbt_ip ]]; then
    echo "INFO: Sin MBT" > /dev/msglog
    mbt=false
    return 1
  else
    echo "INFO: IP de la MBT: ${mbt_ip}" > /dev/msglog
    mbt=true
    return 0
  fi
}

write_mbt () {
  cat > /tmp/mbt-ppp << EOF
noauth
xonxoff
local
lock
mru 256
netmask 255.255.255.0
${concen_mbt_ip}:${mbt_ip}
nodefaultroute
-ac
-pc
-vj
debug
lcp-echo-interval 30
lcp-echo-failure 2
lcp-restart 3
lcp-max-configure 100
lcp-max-failure 10
noaccomp
nobsdcomp
noccp
nodeflate
nopcomp
nopersist
novj
novjccomp
logfile /tmp/ppp-mbt.log
EOF
}

write_env () {
  cat > /home/metro/environment << EOF
UIS_IP=${uis_ip}
CANCELA=${cancela}
TCTI=
MAESTRA_IP=
PLANO=
MBT=${mbt}
EOF
}

main () {
  if check_online; then
    update_app
  fi
  check_app
  deploy_app
  detect_uis
  detect_cancela
  if detect_mbt; then
    write_mbt
  fi
  write_env
  /usr/bin/chown -R metro:metro /home/metro
  ln -sf /home/metro/sun/router.Motif /home/metro/sun/router
  svccfg -s network/rpc/bind setprop config/local_only=false
  svcadm refresh network/rpc/bind:default
}

main

exit $SMF_EXIT_OK
